### ISSUE TITLE
does not work with babel 6, you need to change tag type from es6 to babel

### ISSUE THREAD

**Issue by osiloke** [nilpath/riot-google-maps#8]
does not work with babel 6, you need to change tag type from es6 to babel and also upgrade to riot 2.3.13 because of https://github.com/riot/riot/issues/1394

**Comment by nilpath** [comment]
@osiloke I've totally missed your issues, sorry about that!

I've just commited some changes where I'm no longer defining the type in the riot script tags anymore and I'm not setting the type when compiling the tags instead.

I'm still using the type="es6" and an older version of babel for this project if you want to use babel 6 you can `require 'riot-google-maps/src/index';` and then you can use type babel when compiling your riotjs tags.

**Comment by osiloke** [comment]
cool, i ended up just using a string replace webpack plugin to replace es6 with babel.
